# coding: Windows-31J

# カードのデータ
CardData = [
	{ :name => "カレーライス", :value => 56, :image => "./image/curryandrice.png" },
	{ :name => "わんこそば", :value => 2, :image => "./image/wanko.png" },
	{ :name => "おにぎり", :value => 17, :image => "./image/riceball.png"},
	{ :name => "カルボナーラ", :value => 54, :image => "./image/Carbonara.png" },
	{ :name => "モンブラン", :value => 34, :image => "./image/monburan.png" },
	{ :name => "チャーハン", :value => 42, :image => "./image/friedrice.png" },
	{ :name => "胡麻豆腐", :value => 12, :image => "./image/mabodohu.png" },
	{ :name => "ハンバーガー", :value => 30, :image => "./image/Hamburger.png" },
	{ :name => "おでん", :value => 38, :image => "./image/oden.png" },
	{ :name => "シチュー", :value => 23, :image => "./image/sityu.png" },
	{ :name => "醤油ラーメン", :value => 49, :image => "./image/syouyuraamen.png" },
	{ :name => "コーヒー", :value => 1, :image => "./image/coffee.png" },
	{ :name => "酢豚", :value => 48, :image => "./image/subuta.png" },
	{ :name => "味噌汁", :value => 44, :image => "./image/soup.png" },
	{ :name => "アイスクリーム", :value => 10, :image => "./image/icecream.png" },
	{ :name => "メロンパン", :value => 39, :image => "./image/meronpan.png" },
	{ :name => "わらび餅", :value => 17, :image => "./image/warabimoti.png" },
	{ :name => "冷奴", :value => 9, :image => "./image/hiyayakko.png" },
	{ :name => "納豆", :value => 10, :image => "./image/natto.png" },
	{ :name => "ピザ", :value => 60, :image => "./image/pizza.png" },
	{ :name => "ハムサンド", :value => 7, :image => "./image/sandwich.png" },
	{ :name => "野菜スープ", :value => 9, :image => "./image/yasaisoup.png" },
	{ :name => "クレープ", :value => 24, :image => "./image/kurepu.png" },
	{ :name => "すき焼き", :value => 59, :image => "./image/sukiyaki.png" },
	{ :name => "ハンバーグ", :value => 43, :image => "./image/hambarg.png" },
	{ :name => "オムライス", :value => 69, :image => "./image/omuraisu.png" },
	{ :name => "マカロニグラタン", :value => 50, :image => "./image/guratan.png" },
	{ :name => "鳥の唐揚げ", :value => 5, :image => "./image/karaage.png" },
	{ :name => "きつねうどん", :value => 51, :image => "./image/kituneudon.png" },
	{ :name => "牛丼", :value => 23, :image => "./image/gyuudon.png" },
]
